### ISSUE TITLE
showFile() takes exactly 2 arguments (3 given) in fileselector.py

### ISSUE THREAD

**Issue by Scimmia22** [JeffHoogland/python-elm-extensions#3]
When selecting a file in the fileselector extension, I get this error. Happens either double clicking or selecting and hitting Save. Using python 2.7.9.

```
Traceback (most recent call last):
  File "efl/elementary/object.pyx", line 316, in efl.elementary.object._object_callback (efl/elementary/object.c:7651)
  File "/home/dnewgard/python-elm-extensions/elmextensions/fileselector.py", line 365, in fileDoubleClicked
    self.actionButtonPressed(self.actionButton)
  File "/home/dnewgard/python-elm-extensions/elmextensions/fileselector.py", line 484, in actionButtonPressed
    self.actionCallback(self, "%s%s"%(self.filepathEntry.text, self.fileEntry.text))
TypeError: showFile() takes exactly 2 arguments (3 given)
```

**Comment by JeffHoogland** [comment]
Fixed. Forgot to update the test file when I had the callback return the FS object as the first argument.
